import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className={"bg-blue-500"}>
      <Head>
        <title>Rock-Paper-scissors-Lizard-Spock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        <div>
          <p> Rock ,Paper , Scissors , Lizard , Spock </p>
        </div>

      </main>

    </div>
  )
}

export default Home
